version: 0.0
os: linux
files:
  - source: /
    destination: /usr/lib/node_modules/node-red
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: ec2-user
#   ApplicationStart:
#     - location: scripts/applicationstart.sh
#       timeout: 300
#       runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root
